# Generated by Django 4.0.4 on 2022-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
