# Generated by Django 4.0.4 on 2022-05-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_birthdate_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
    ]
