# Generated by Django 4.0.4 on 2022-05-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='vault',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
