# Generated by Django 4.0.4 on 2022-05-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_account_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='creation_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_expiration_date', models.DateTimeField(null=True)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
        ),
    ]
