# Generated by Django 4.0.4 on 2022-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_timestamp_externaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransaction',
            name='external_peer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
