# Generated by Django 4.0.4 on 2022-05-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ask_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bid_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_change',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_change_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_price',
            field=models.FloatField(),
        ),
    ]
